import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{initializeApp}from'firebase/app';
import{getAuth,signInAnonymously}from'firebase/auth';
import{getFirestore,collection,addDoc,onSnapshot,serverTimestamp,query,orderBy}from'firebase/firestore';
import{Gamepad2,Trophy,Star,ShoppingBag,ScrollText,ShieldCheck}from'lucide-react';
import'./style.css';
const firebaseConfig={apiKey:'AIzaSyCQ5JkNl0ZvWbixOBZumSjtoNiXMyotJWQ',authDomain:'family-quest-b78d8.firebaseapp.com',projectId:'family-quest-b78d8',storageBucket:'family-quest-b78d8.firebasestorage.app',messagingSenderId:'98347120366',appId:'1:98347120366:web:9ebfdb716823778d45a5ff'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const FAMILY='mae-alix-family';
const missions=[['Mettre la table',2,'🍽️'],['Débarrasser toute la table',3,'🧹'],['Débarrasser le lave-vaisselle',4,'✨'],['Étendre le linge',4,'👕'],['Plier le linge',4,'🧺'],['Ranger son linge',2,'🗄️'],['Sortir poubelle / tri',3,'♻️'],['Aspirateur étage',5,'🌀'],['Passer la serpillière',5,'💧'],['Nettoyer une salle de bain',6,'🛁'],['Aider au repas',3,'🥗'],['Initiative / entraide',2,'🤝'],['Affaires laissées à traîner',-1,'💀'],['Lumière laissée allumée',-1,'💡'],['Linge non rangé après rappel',-2,'⚠️']];
const rewards=[['Goûter spécial',100,'🍦'],['Soirée film + repas',200,'🍿'],['Glace / crêpe / bubble tea',300,'🧋'],['Cinéma',450,'🎬'],['Jump / bowling / laser game',600,'🎳'],['Restaurant choisi',750,'🍕'],['Parc / zoo / activité',1200,'🎢'],['Week-end / grande activité',1800,'🗺️'],['Disney',3000,'🏰']];
function App(){const[events,setEvents]=useState([]),[who,setWho]=useState('Maé'),[tab,setTab]=useState('missions'),[ready,setReady]=useState(false);useEffect(()=>{signInAnonymously(auth).then(()=>setReady(true))},[]);useEffect(()=>{if(!ready)return;return onSnapshot(query(collection(db,'families',FAMILY,'events'),orderBy('createdAt','desc')),s=>setEvents(s.docs.map(d=>({id:d.id,...d.data()}))))},[ready]);
const earned=events.filter(e=>e.kind==='mission').reduce((a,e)=>a+(e.points||0),0),spent=events.filter(e=>e.kind==='reward').reduce((a,e)=>a+(e.cost||0),0),balance=earned-spent;const scores=useMemo(()=>Object.fromEntries(['Maé','Alix'].map(n=>[n,events.filter(e=>e.kind==='mission'&&e.player===n).reduce((a,e)=>a+(e.points||0),0)])),[events]);
const addMission=async m=>addDoc(collection(db,'families',FAMILY,'events'),{kind:'mission',player:who,label:m[0],points:m[1],createdAt:serverTimestamp()});const buy=async r=>{if(balance<r[1])return alert('Pas encore assez de pièces !');if(confirm(`Dépenser ${r[1]} points pour ${r[0]} ?`))await addDoc(collection(db,'families',FAMILY,'events'),{kind:'reward',label:r[0],cost:r[1],createdAt:serverTimestamp()})};const pct=Math.min(balance/3000*100,100);const level=balance<300?'Explorateurs':balance<750?'Aventuriers':balance<1500?'Champions':balance<3000?'Légendes':'Maîtres de la maison';
return <div className="app"><header><div><small>FAMILY QUEST</small><h1><Gamepad2/> La quête de la maison</h1></div><div className="coins">🪙 {balance}</div></header><section className="hero"><div className="castle">🏰</div><div className="grow"><b>QUÊTE ÉPIQUE · DISNEY</b><div className="bar"><i style={{width:pct+'%'}}/></div><span>{balance} / 3000 XP · {Math.round(pct)}%</span></div></section><section className="players">{['Maé','Alix'].map((n,i)=><button className={who===n?'selected':''} onClick={()=>setWho(n)} key={n}><span className="avatar">{i?'🧝‍♀️':'🧙‍♀️'}</span><b>{n}</b><small>{scores[n]} XP</small></button>)}</section><div className="rank"><Trophy/> Rang famille : <b>{level}</b></div><nav><button onClick={()=>setTab('missions')} className={tab==='missions'?'on':''}><Star/>Missions</button><button onClick={()=>setTab('shop')} className={tab==='shop'?'on':''}><ShoppingBag/>Boutique</button><button onClick={()=>setTab('history')} className={tab==='history'?'on':''}><ScrollText/>Journal</button></nav>{tab==='missions'&&<main><h2>⚔️ Missions de {who}</h2><p className="hint">Touchez une mission lorsqu'elle est terminée.</p><div className="grid">{missions.map(m=><button className={m[1]<0?'mission bad':'mission'} onClick={()=>addMission(m)} key={m[0]}><span>{m[2]}</span><div><b>{m[0]}</b><small>{m[1]>0?'+':''}{m[1]} XP</small></div></button>)}</div></main>}{tab==='shop'&&<main><h2>🎁 Boutique des récompenses</h2><div className="grid">{rewards.map(r=><button className="mission reward" onClick={()=>buy(r)} key={r[0]}><span>{r[2]}</span><div><b>{r[0]}</b><small>🪙 {r[1]}</small></div></button>)}</div></main>}{tab==='history'&&<main><h2>📜 Journal d'aventure</h2>{events.slice(0,50).map(e=><div className="event" key={e.id}><span>{e.kind==='reward'?'🎁':e.points<0?'💀':'⭐'}</span><div><b>{e.kind==='mission'?`${e.player} · ${e.label}`:`Récompense · ${e.label}`}</b><small>{e.kind==='reward'?`-${e.cost} pièces`:`${e.points>0?'+':''}${e.points} XP`}</small></div></div>)}</main>}<footer><ShieldCheck/> Synchronisé avec la famille · Firebase</footer></div>}
createRoot(document.getElementById('root')).render(<App/>);
